version: '2'
services:
  web:taxifleetmanager
    container_name:
    environment:
      - DB_HOST_NAME=TAXIFLEETMANAGERDashboardMongoDB
      - DB_PORT=27017
#      - BUS_PARKING_GATWAY_URL="http://118.201.198.248:8000/smrt/parkingbaystatus.php"
    depends_on:
    - mongo
    build: .
    image: registry.gitlab.com/necdockerimage/taxifleetmanager
    ports:
      - "4200:4200"    # web application Port
      - "4202-4209:4202-4209"  # ZMQ ports for incoming data
    volumes:
    - .:/code
    #- logvolume01:/var/log
    links:
    - mongo
  mongo:
    image: mongo
    container_name: TAXIFLEETMANAGERDashboardMongoDB
   # name:ncecp-nongo
    volumes:
    - ~/data/mongo/TAXIFLEETMANAGERDashboardDb/:/data/db
    #- ~/data/mongo/dbconfig:/data/configdb
    ports:
    - "27028:27018"
#volumes:
 # logvolume01: {}